/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CopiloteRouteImport } from './routes/copilote'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RelanceRouteImport } from './routes/relance'
import { Route as ServiceClientRouteImport } from './routes/service-client'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CopiloteRoute = CopiloteRouteImport.update({
  id: '/copilote',
  path: '/copilote',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RelanceRoute = RelanceRouteImport.update({
  id: '/relance',
  path: '/relance',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceClientRoute = ServiceClientRouteImport.update({
  id: '/service-client',
  path: '/service-client',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/copilote': typeof CopiloteRoute
  '/devis': typeof DevisRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/relance': typeof RelanceRoute
  '/service-client': typeof ServiceClientRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/copilote': typeof CopiloteRoute
  '/devis': typeof DevisRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/relance': typeof RelanceRoute
  '/service-client': typeof ServiceClientRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/copilote': typeof CopiloteRoute
  '/devis': typeof DevisRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/relance': typeof RelanceRoute
  '/service-client': typeof ServiceClientRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/copilote'
    | '/devis'
    | '/leads'
    | '/login'
    | '/relance'
    | '/service-client'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/copilote'
    | '/devis'
    | '/leads'
    | '/login'
    | '/relance'
    | '/service-client'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/copilote'
    | '/devis'
    | '/leads'
    | '/login'
    | '/relance'
    | '/service-client'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CopiloteRoute: typeof CopiloteRoute
  DevisRoute: typeof DevisRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  RelanceRoute: typeof RelanceRoute
  ServiceClientRoute: typeof ServiceClientRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilote': {
      id: '/copilote'
      path: '/copilote'
      fullPath: '/copilote'
      preLoaderRoute: typeof CopiloteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relance': {
      id: '/relance'
      path: '/relance'
      fullPath: '/relance'
      preLoaderRoute: typeof RelanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-client': {
      id: '/service-client'
      path: '/service-client'
      fullPath: '/service-client'
      preLoaderRoute: typeof ServiceClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CopiloteRoute: CopiloteRoute,
  DevisRoute: DevisRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  RelanceRoute: RelanceRoute,
  ServiceClientRoute: ServiceClientRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
